Disertatie/Models/EvaluareProiect.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Disertatie.Models
{
    public class EvaluareProiect
    {
        public long IdProiect { get; set; }
        public int Evaluare { get; set; }
        public int TotalEvaluatori { get; set; }
        public double EvaluareMedie { get; set; }

    }
}

Disertatie/Models/NoutatiProiecte.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Disertatie.Models
{
    public class NoutatiProiecte
    {
        public Disertatie.Core.Models.Proiect Proiect { get; set; }
        public string Mesaj { get; set; }
    }
}

Disertatie/Controllers/MesajeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Disertatie.Mvc;
using Disertatie.Core.Repositories;
using Disertatie.Core;
using Disertatie.Core.Models;
using Disertatie.Models;

namespace Disertatie.Controllers
{
    public class MesajeController : Controller
    {
        //
        // GET: /Mesaje/

        public ActionResult Index()
        {
            return View();
        }
         [Authorize(Roles = "Administrator,Membru, Sef departament, Coordonator colectiv")]
        [NHibernateSession]
        public ActionResult StergeMesaj(long id, int? page1, int? page2, int? page3)
        {
            var mesajeRep = new Repository<long, Mesaj>();
            var mesaj = mesajeRep.Get(id);
            mesaj.Activ = false;
            mesajeRep.Update(mesaj);

            var repo = new UtilizatorRepository();
            var user = SecurityContext.CurrentUser as Utilizator;
            var model = new MembruHomeModel();
           var zeroBasePageIndex1 = Math.Max((page1 ?? 1) - 1, 0);
            var zeroBasePageIndex2 = Math.Max((page2 ?? 1) - 1, 0);
            var zeroBasePageIndex3 = Math.Max((page3 ?? 1) - 1, 0);
            model.MesajeNoi = repo.GetMesajeNoi(zeroBasePageIndex1,10,user);
            model.MesajePrimite = repo.GetMesajePrimite(zeroBasePageIndex2,10,user);
            model.MesajeTrimise = repo.GetMesajeTrimise(zeroBasePageIndex3,10,user);
            model.Utilizator = user;
            model.EstePaginaDeProfil = true;
            return View("MesajSters",model);
        }
        [NHibernateSession]
        public void MarcareCitit(string strId)
        {

            try
            {

                var mesajeRep = new Repository<long, Mesaj>();
                var mesaj = mesajeRep.Get(Convert.ToInt64(strId));
                mesaj.Citit = true;
                mesajeRep.Update(mesaj);

            }
            catch (Exception)
            {
            }

           
            
        }

    }
}

Disertatie/Controllers/ProiecteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Disertatie.Models;
using Disertatie.Core.Repositories;
using Disertatie.Core.Models;
using System.Globalization;
using Disertatie.Mvc;
using Disertatie.Core;
using System.IO;
using System.Configuration;

namespace Disertatie.Controllers
{
    public class ProiecteController : Controller
    {
        //
        // GET: /Proiecte/

        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Administrator,Membru, Sef departament, Coordonator colectiv")]
        [NHibernateSession]
        public ActionResult Proiecte(int? page1, int? page2, int? page3, int? page4)
        {

            var repo = new UtilizatorRepository();
            var user = SecurityContext.CurrentUser as Utilizator;
            var model = new MembruHomeModel();
            var zeroBasePageIndex1 = Math.Max((page1 ?? 1) - 1, 0);
            var zeroBasePageIndex2 = Math.Max((page2 ?? 1) - 1, 0);
            var zeroBasePageIndex3 = Math.Max((page3 ?? 1) - 1, 0);
            var zeroBasePageIndex4 = Math.Max((page4 ?? 1) - 1, 0);
            model.ProiectePropuse = repo.GetProiectePropuse(zeroBasePageIndex1, 10,user);
            model.ProiecteInchise = repo.GetProiecteInchise(zeroBasePageIndex2, 10, user);
            model.ProiecteInLucru = repo.GetProiecteInLucru(zeroBasePageIndex3, 10, user);
            model.ProiecteAnulate = repo.GetProiecteAnulate(zeroBasePageIndex4, 10, user);
            model.Utilizator = user;
            model.EstePaginaCuProiecte = true;
            return View(model);
        }
        [Authorize(Roles = "Administrator,Membru, Sef departament, Coordonator colectiv")]
        [NHibernateSession]
        public ActionResult GetProiecteleMele(int? page1, int? page2, int? page3, int? page4)
        {

            var repo = new UtilizatorRepository();
            var user = SecurityContext.CurrentUser as Utilizator;
            var model = new MembruHomeModel();
            var zeroBasePageIndex1 = Math.Max((page1 ?? 1) - 1, 0);
            var zeroBasePageIndex2 = Math.Max((page2 ?? 1) - 1, 0);
            var zeroBasePageIndex3 = Math.Max((page3 ?? 1) - 1, 0);
            var zeroBasePageIndex4 = Math.Max((page4 ?? 1) - 1, 0);
            model.ProiectePropuse = repo.GetProiectePropuse(zeroBasePageIndex1, 10, user);
            model.ProiecteInchise = repo.GetProiecteInchise(zeroBasePageIndex2, 10, user);
            model.ProiecteInLucru = repo.GetProiecteInLucru(zeroBasePageIndex3, 10, user);
            model.ProiecteAnulate = repo.GetProiecteAnulate(zeroBasePageIndex4, 10, user);
            model.Utilizator = user;
            model.EstePaginaCuProiecte = true;
            return View(model);
        }
        [Authorize(Roles = "Administrator,Membru, Sef departament, Coordonator colectiv")]
        [NHibernateSession]
        public ActionResult GetProiecteleInColaborare(int? page1, int? page2, int? page3, int? page4)
        {

            var repo = new UtilizatorRepository();
            var user = SecurityContext.CurrentUser as Utilizator;
            var model = new MembruHomeModel();
            var zeroBasePageIndex1 = Math.Max((page1 ?? 1) - 1, 0);
            var zeroBasePageIndex2 = Math.Max((page2 ?? 1) - 1, 0);
            var zeroBasePageIndex3 = Math.Max((page3 ?? 1) - 1, 0);
            var zeroBasePageIndex4 = Math.Max((page4 ?? 1) - 1, 0);
            model.ProiectePropuse = repo.GetProiecteInColaborarePropuse(zeroBasePageIndex1, 10, user);
            model.ProiecteInchise = repo.GetProiecteInColaborareInchise(zeroBasePageIndex2, 10, user);
            model.ProiecteInLucru = repo.GetProiecteInColaborareInLucru(zeroBasePageIndex3, 10, user);
            model.ProiecteAnulate = repo.GetProiecteInColaborareAnulate(zeroBasePageIndex4, 10, user);
            model.Utilizator = user;
            model.EstePaginaCuProiecte = true;
            return View(model);
        }
        [Authorize(Roles = "Administrator,Membru, Sef departament, Coordonator colectiv")]
        [NHibernateSession]
        public ActionResult ProiecteMembru(string idUtilizator, int? page)
        {
            if (idUtilizator != null)
                Session["idUtilizator"] = idUtilizator;
            var repo = new UtilizatorRepository();
            var model = new MembruHomeModel();
            var user = SecurityContext.CurrentUser as Utilizator;
            var zeroBasePageIndex = Math.Max((page ?? 1) - 1, 0);
            var membru = repo.Get(Convert.ToInt64(idUtilizator == null ? Session["idUtilizator"] : idUtilizator));
            model.ProiecteMembru = repo.GetProiecteMembru(zeroBasePageIndex, 10, membru);
            model.Utilizator = user;
            model.MembruCuProiecte = membru;
            model.EstePaginaCuProiecte = true;
            return View(model);

        }
        [Authorize(Roles = "Administrator,Membru, Sef departament, Coordonator colectiv")]
        [NHibernateSession]
        public ActionResult Detaliiproiect(string id)
        {
            var proiecteRep = new Repository<long, Proiect>();
            var proiect = proiecteRep.Get(Convert.ToInt64(id));
            var model = new MembruHomeModel();
            var user = SecurityContext.CurrentUser as Utilizator;
            model.Utilizator = user;
            model.Proiect = proiect;
            var membriiRep = new Repository<long, Disertatie.Core.Models.MembriiProiect>();
            model.MembriiProiect = membriiRep.QueryAll().Where(a => a.Proiect == proiect && a.Activ==true).Select(a => a.Utilizator).ToList();
            var membruExistent = membriiRep.QueryAll().Where(a => a.Proiect == proiect && a.Activ==true && a.Utilizator==user).FirstOrDefault();
            model.EsteDejaMembru = membruExistent != null ? true : false;
            model.CreeazaProiectModel = new CreeazaProiectModel();
            var obiectiveRep=new Repository<long,ObiectivProiect>();
            model.CreeazaProiectModel.ObiectiveGenerale = obiectiveRep.QueryAll().Where(a => a.Proiect == proiect && a.Tip==1 && a.Activ==true).ToList();
            model.CreeazaProiectModel.ObiectiveSpecifice = obiectiveRep.QueryAll().Where(a => a.Proiect == proiect && a.Tip==2 && a.Activ==true).ToList();
            model.EvaluareProiect = new EvaluareProiect();
            model.EvaluareProiect.IdProiect = proiect.Id;
            model.EvaluareProiect.Evaluare = proiect.Evaluare;
            model.EvaluareProiect.TotalEvaluatori = proiect.TotalEvaluatori;
            model.EvaluareProiect.EvaluareMedie = Convert.ToDouble(proiect.Evaluare) / Convert.ToDouble(proiect.TotalEvaluatori);
            var docIncarcateRep = new Disertatie.Core.Repositories.Repository<long, DocumentIncarcat>();
            var doc = docIncarcateRep.QueryAll().Where(a => a.Proiect == proiect && a.Activ == true).ToList();
            model.DocumenteIncarcate = doc;
            var comentariuRep = new Disertatie.Core.Repositories.Repository<long, ComentariuProiect>();
            model.ComentariiProiect = new List<ComentariuProiect>();
            model.ComentariiProiect = comentariuRep.QueryAll().Where(a => a.Proiect == model.Proiect && a.Activ == true).OrderBy(a => a.DataCrearii).ToList();
            model.EstePaginaCuProiecte = true;
            return View(model);
        }
        [Authorize(Roles = "Administrator,Membru, Sef departament, Coordonator colectiv")]
        [NHibernateSession]
        public ActionResult DetaliiProiectInvitatii(string id)
        {
            var proiecteRep = new Repository<long, Proiect>();
            var proiect = proiecteRep.Get(Convert.ToInt64(id));
            var model = new MembruHomeModel();
            var user = SecurityContext.CurrentUser as Utilizator;
            model.Utilizator = user;
            model.Proiect = proiect;
            var membriiRep = new Repository<long, Disertatie.Core.Models.MembriiProiect>();
            model.MembriiProiect = membriiRep.QueryAll().Where(a => a.Proiect == proiect && a.Activ == true).Select(a => a.Utilizator).ToList();
            var membruExistent = membriiRep.QueryAll().Where(a => a.Proiect == proiect && a.Activ == true && a.Utilizator == user).FirstOrDefault();
            model.EsteDejaMembru = membruExistent != null ? true : false;
            model.CreeazaProiectModel = new CreeazaProiectModel();
            var obiectiveRep = new Repository<long, ObiectivProiect>();
            model.CreeazaProiectModel.ObiectiveGenerale = obiectiveRep.QueryAll().Where(a => a.Proiect == proiect && a.Tip == 1 && a.Activ == true).ToList();
            model.CreeazaProiectModel.ObiectiveSpecifice = obiectiveRep.QueryAll().Where(a => a.Proiect == proiect && a.Tip == 2 && a.Activ == true).ToList();
            model.EvaluareProiect = new EvaluareProiect();
            model.EvaluareProiect.IdProiect = proiect.Id;
            model.EvaluareProiect.Evaluare = proiect.Evaluare;
            model.EvaluareProiect.TotalEvaluatori = proiect.TotalEvaluatori;
            model.EvaluareProiect.EvaluareMedie = Convert.ToDouble(proiect.Evaluare) / Convert.ToDouble(proiect.TotalEvaluatori);
            var docIncarcateRep = new Disertatie.Core.Repositories.Repository<long, DocumentIncarcat>();
            var doc = docIncarcateRep.QueryAll().Where(a => a.Proiect == proiect && a.Activ == true).ToList();
            model.DocumenteIncarcate = doc;
            var comentariuRep = new Disertatie.Core.Repositories.Repository<long, ComentariuProiect>();
            model.ComentariiProiect = new List<ComentariuProiect>();
            model.ComentariiProiect = comentariuRep.QueryAll().Where(a => a.Proiect == model.Proiect && a.Activ == true).OrderBy(a => a.DataCrearii).ToList();
            model.EstePaginaCuProiecte = true;
            return View(model);
        }
        [Authorize(Roles = "Administrator,Membru, Sef departament, Coordonator colectiv")]

Disertatie/Views/Shared/AfisareEvaluareProiect.cshtml
@model Disertatie.Models.EvaluareProiect
@using Disertatie.Helpers
@*<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js" type="text/javascript"></script>*@



  <div id="rated">
  <div style="float:left">
    <form id="Form1" method="post" action="">
      <input class="star {split:4}" type="radio" value="1" name="rating"  @Utils.Check(0,0.25,Model.EvaluareMedie)/>
      <input class="star {split:4}" type="radio" value="2" name="rating"  @Utils.Check(0.25,0.5,Model.EvaluareMedie)/>
      <input class="star {split:4}" type="radio" value="3" name="rating"  @Utils.Check(0.5,0.75,Model.EvaluareMedie)/>
      <input class="star {split:4}" type="radio" value="4" name="rating" @Utils.Check(0.75,1,Model.EvaluareMedie) />
      <input class="star {split:4}" type="radio" value="5" name="rating" @Utils.Check(1,1.25,Model.EvaluareMedie)/>
      <input class="star {split:4}" type="radio" value="6" name="rating" @Utils.Check(1.25,1.5,Model.EvaluareMedie) />
      <input class="star {split:4}" type="radio" value="7" name="rating" @Utils.Check(1.5,1.75,Model.EvaluareMedie) />
      <input class="star {split:4}" type="radio" value="8" name="rating" @Utils.Check(1.75,2,Model.EvaluareMedie) />
      <input class="star {split:4}" type="radio" value="9" name="rating" @Utils.Check(2,2.25,Model.EvaluareMedie) />
      <input class="star {split:4}" type="radio" value="10" name="rating" @Utils.Check(2.25,2.5,Model.EvaluareMedie) />
      <input class="star {split:4}" type="radio" value="11" name="rating" @Utils.Check(2.5,2.75,Model.EvaluareMedie) />
      <input class="star {split:4}" type="radio" value="12" name="rating" @Utils.Check(2.75,3,Model.EvaluareMedie)/>
      <input class="star {split:4}" type="radio" value="13" name="rating" @Utils.Check(3,3.25,Model.EvaluareMedie) />
      <input class="star {split:4}" type="radio" value="14" name="rating" @Utils.Check(3.25,3.5,Model.EvaluareMedie) />
      <input class="star {split:4}" type="radio" value="15" name="rating" @Utils.Check(3.5,3.75,Model.EvaluareMedie) />
      <input class="star {split:4}" type="radio" value="16" name="rating" @Utils.Check(3.75,4,Model.EvaluareMedie) />
      <input class="star {split:4}" type="radio" value="17" name="rating" @Utils.Check(4,4.25,Model.EvaluareMedie) />
      <input class="star {split:4}" type="radio" value="18" name="rating" @Utils.Check(4.25,4.5,Model.EvaluareMedie) />
      <input class="star {split:4}" type="radio" value="19" name="rating" @Utils.Check(4.5,4.75,Model.EvaluareMedie) />
      <input class="star {split:4}" type="radio" value="20" name="rating" @Utils.Check(4.75,5,Model.EvaluareMedie) />
      </form>
    </div>
    <p id="currentlyrated" style="float:left;padding-left:20px;">
    @if (Model.EvaluareMedie > 0 )
    {
   <span>Evaluat la @Model.EvaluareMedie.ToString("f") de @Model.TotalEvaluatori persoane</span>
    }
    else
    {
        <span style="color:red">Nu a fost inca evaluat.  Fii primul care evalueaza acest proiect!</span>
    }
    </p>
  </div>
  <div style="clear:both"></div>
  
  <div id="rater">
    <div style="float:left;">
      <form id="rate" method="post" action="">
      <input class="auto-submit-star" type="radio" name="score" value="1"/>
      <input class="auto-submit-star" type="radio" name="score" value="2"/>
      <input class="auto-submit-star" type="radio" name="score" value="3"/>
      <input class="auto-submit-star" type="radio" name="score" value="4"/>
      <input class="auto-submit-star" type="radio" name="score" value="5"/>
      <input type="hidden" name="IdProiect" value="@Model.IdProiect" />
      </form>
    </div>
    <p style="float:left;padding-left:20px;">
      Voteaza acum!
    </p>
  </div>
  <div style="clear:both"></div>

  <script type="text/javascript">

      $(function () {
          $('.star').rating('readOnly', true);
          $('#rater').hide();
//          $('#rated').mouseover(function () {
//              $('#rated').hide();
//              $('#rater').show();
//          });
//          $('#rated').mouseenter(function () {
//              $('#rated').hide();
//              $('#rater').show();
//          });
//          $('#rater').mouseleave(function () {
//              $('#rater').hide();
//              $('#rated').show();
//          });

          $('.auto-submit-star').rating({
              callback: function (value, link) {
                  $.ajax({
                      type: "POST",
                      url: '@Url.Action("Evaluare", "Proiecte")',
                      data: $("#rate").serialize(),
                      dataType: "text/plain",
                      success: function (response) {
                          if (response != 'false') {
                              var data = eval('(' + response + ')');
                              alert('Nota a fost inregistrata');
                              $('#currentlyrated').html('Evaluat la ' + data.EvaluareMedie.toFixed(2) +
                ' de ' + data.TotalRaters + ' persoane');
                          } else {
                              alert('Ai mai votat o data acest proiect!');
                          }
                          $('#rater').hide();
                          $('#rated').show();
                      },
                      error: function (response) {
                          alert('A fost o eroare.');
                      }
                  });
              }
          });
      });
</script>

Disertatie/Views/Shared/DocumenteIncarcate.cshtml
@model IEnumerable<Disertatie.Core.Models.DocumentIncarcat>
@using Disertatie.Helpers


<div id="doc_header">
<b style="font-size: 12px;margin: 5px;display: inline;">Documente incarcate</b>
</div>
<table id="doc_table_header" cellspacing="0" cellpadding="0">
	<tbody>
    <tr>
 <th width="50">&nbsp;</th>
<th width="300">Nume</th>
<th width="200">Incarcat</th>
<th class="last">&nbsp;</th>
</tr>
@foreach (var item in Model)
{
    <tr>
    <td class="left">
    <a href="@item.Cale" class="btn">Descarca</a>
    </td>
    <td>
    @item.Nume
    </td>
    <td>
    de <a href="@Url.Action("DetaliiMembru", "Home", new { id = item.Utilizator.Id })" >@item.Utilizator.Nume @item.Utilizator.Prenume </a> la @item.DataIncarcarii
    </td>
    
    <td>
    @if (HttpContext.Current.User.Identity.Name  == item.Proiect.Initiator.Username || HttpContext.Current.User.Identity.Name == item.Utilizator.Username)
    {
      
     @Html.ActionLink("Sterge", "StergeDocument", "Proiecte", new { id = item.Id }, new { @class = "delete" })
    }
    </td>
    
    </tr>
}
</tbody>
</table>
   

Disertatie/Views/Shared/MembriiDepartamentList.cshtml
@using Disertatie.Core.Models
@model IEnumerable<Utilizator> 
   
 <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-ui.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>


   <table style="width: 100%;" cellpadding="0" cellspacing="0" border="0">
    <thead>
        <tr>
            <th class="capt" colspan="6">
                Lista membrii departament
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="left" style="width: 60">
                    @if (string.IsNullOrEmpty(item.PozaProfil))
                    {
                        <img src="@Url.Content("~/Content/Images/NoPhoto.jpeg")" alt="" align="left" width="50" height="50" />
                    }
                    else
                    {
                        <img align="left" width="50" height="50" src="@item.PozaProfil" alt="" />
                    }
                </td>
                <td class="left">
                    <ul style="list-style-type: none;">
                        <li><span class="nameText">
                          <a href="@Url.Action("DetaliiMembru", "Home",new {id= @item.Id})" style=" color: #5777BB;">  @string.Format("{0} {1}", item.Nume, item.Prenume)</a>
                        </span></li>
                        <li><span class="textLinks">Colectiv: @string.Format("({0})", item.Colectiv.Nume)
                        </span></li>
                        <li >
                        <a href="@Url.Action("ProiecteMembru", "Proiecte", new { idUtilizator = item.Id })">
<img id="arrow" src="@Url.Content("~/Content/Images/arrow_small.gif")" alt="" />
Proiecte
</a>

                       @* @Html.ActionLink("Proiecte", "ProiecteMembru", "Proiecte", new { idUtilizator = item.Id })*@
                       <img id="arrow" src="@Url.Content("~/Content/Images/arrow_small.gif")" alt="" />
                        @Html.ActionLink("Trimite mesaj", "TrimiteMesaj", "Home", new { idDestinatar = item.Id }, new { @class = "openDialog", data_dialog_id = "emailDialog", data_dialog_title = "Trimite mesaj" })
                        
                        </li>
                    </ul>
                </td>
            </tr>
          
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="6">
                @Html.Partial("Pagination", Model)
            </td>
        </tr>
    </tfoot>
</table>

	

<script type="text/javascript">

    $.ajaxSetup({ cache: false });

    $(document).ready(function () {
        $(".openDialog").live("click", function (e) {
            e.preventDefault();

            $("<div></div>")
                .addClass("dialog")
                .attr("id", $(this).attr("data-dialog-id"))
                .appendTo("body")
                .dialog({
                    title: $(this).attr("data-dialog-title"),
                    close: function () { $(this).remove() },
                    modal: true,
                    width: '430px'
                })
                .load(this.href);
        });

        $(".close").live("click", function (e) {
            e.preventDefault();
            $(this).closest(".dialog").dialog("close");
        });
    });
</script>

 

Disertatie/Views/Shared/MesajeTrimiseList.cshtml
@model IEnumerable<Disertatie.Core.Models.Mesaj>
@using Disertatie.Helpers


<table id="mesajeTrimise">
	
    <thead>
		<tr>
			<th scope="col" style="width: 20px; max-width: 20px;">
                        <a id="expand_all" href="#">+</a>
				
			</th>
			<th>
				Trimis la
			</th>
			<th>
				Expeditor
			</th>
			
			<th>
				Titlu
			</th>
            <th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model) {
	
         <tr>
				<td style="width: 20px;" align="center">
                <a class="expand"  id="hLinkExpand" href="#" >
                <img src="../Content/images/plus_ico.png"/ alt="" />
                
                </a> 
 
                
            </td>
				<td>
					@item.DataTrimitere.ToString("dd-MM-yyyy HH:mm")
				</td>
				<td>
					@string.Format("{0} {1}", @item.Expeditor.Nume, @item.Expeditor.Prenume)
				</td>
				<td>
					@item.Titlu
				</td>                
				<td>
                @Html.ActionLink("Sterge", "StergeMesaj", "Mesaje", new { id = item.Id }, new { @class = "delete" })
                </td>
				
			</tr>
       <tr class="doc-details" style="display:none">
           
            <td colspan="8" style="text-align:left;">
                
               @item.Detalii
               
            </td>
        </tr>
      
  }
	</tbody>
    <tfoot>
        <tr>
            <td colspan="6" >
                @Html.Partial("PaginationMesajeTrimise", Model)
            </td>
        </tr>
    </tfoot>
</table>

<script type="text/javascript">
    var childWindow = null;
    var isPostBack = false;
    var plus_img_url = "../Content/images/plus_ico.png";
    var minus_img_url = "../Content/images/minus_ico.png";


    $(function () {
        window.onunload = function (event) {
            if (!isPostBack) {
                if (childWindow != null) childWindow.close();
            }
        }

        $('#toggle-advanced-filters').click(function (e) {
            e.preventDefault();
            $('#advanced-filters').slideToggle('fast');
            if ($(this).text() == 'Arata alte filtre') {
                $(this).text('Ascunde alte filtre');
            } else {
                $(this).text('Arata alte filtre');
            }
        });

        $('#mesajeTrimise a.expand').click(function (event) {
            event.preventDefault();
            var href = $(this).attr('href');
            var img = $('img', $(this));
            var mainRow = $(this).parent().parent();
            var tableRow = mainRow.next();

            if (img.attr('src') != minus_img_url) {
                // expanding
                var ajaxError = false;
                img.attr('src', minus_img_url);
                // se deschide randul, se va afisa automat mesajul "loading" (e pus acolo)
                var details = tableRow.toggle().find('.doc-details');
                //var tr = document.getElementById('trDetailsMesajePrimite');
                //tr.style.display = 'table-row';
                // se cauta in copii "div.doc-details-inner", dak nu exista atunci trebuie adus via AJAX dp server

                // deschide detaliile din rand
                details.toggle();
            } else {
                // collapsing
                img.attr('src', plus_img_url);
                //var tr = document.getElementById('trDetailsMesajePrimite');
                //tr.style.display = 'none';
                tableRow.find('.doc-details').slideToggle();
                tableRow.toggle();
            }
        });

    });

    function showSendMailModal(row, politaUrl) {
        alert('mail');

    }

    function hideMailForm(hide) {
        alert('hide mial');

    }

    function setAdvancedFilters(value) {
        alert('advace filtring');

    }
</script>

Disertatie/Views/Shared/ProiecteInColaborareDeschiseList.cshtml
@model IEnumerable<Disertatie.Core.Models.Proiect>
@using Disertatie.Helpers


<table id="services">
	
    <thead>
		<tr>
			<th>
				
			</th>
          
			<th>
				Creat la
			</th>
			<th>
				Titlu
			</th>
			
			<th>
			    Director
			</th>
            
           
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model) {
	
         <tr>
				<td style="background-color: #E4E6CC;">
					@Html.ActionLink("Detalii", "DetaliiProiecteInColaborare", "Proiecte", new { id = item.Id }, null)
                </td>
              
				<td>
					@item.DataCreare.ToString("dd-MM-yyyy HH:mm")
				</td>
				<td>
					@item.Titlu
				</td>
				<td>
					@item.Initiator.Nume @item.Initiator.Prenume
				</td>                
				
				
			</tr>
      
  }
	</tbody>
     <tfoot>
        <tr>
            <td colspan="4">
                @Html.Partial("PaginationProiecteInColaborarePropuse", Model)
            </td>
        </tr>
    </tfoot>
</table>